spring.messages.basename=messages/ValidationMessages
spring.messages.encoding=UTF-8

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

spring.datasource.hikari.connection-timeout=5000
spring.datasource.hikari.maximum-pool-size=10

